import { Images } from "../../../assets";

export const workerProfileData = [
  {
    id: "1",
    name: "John",
    country: "United States",
    profileIcon: Images.person1,
    flagIcon:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/320px-Flag_of_the_Taliban.svg.png",
    category: "Photographer",
  },
  {
    id: "2",
    name: "Jane",
    country: "India",
    profileIcon: Images.person2,
    flagIcon: "https://flagcdn.com/w320/ax.png",
    category: "Makeup",
  },
  {
    id: "3",
    name: "Carlos",
    country: "Mexico",
    profileIcon: Images.person3,
    flagIcon: "https://flagcdn.com/w320/al.png",
    category: "Astrologer",
  },
  {
    id: "4",
    name: "Yuki",
    country: "Japan",
    profileIcon: Images.person4,
    flagIcon: "https://flagcdn.com/w320/dz.png",
    category: "Assistant",
  },
  {
    id: "5",
    name: "Maria",
    country: "Italy",
    profileIcon: Images.person5,
    flagIcon: "https://flagcdn.com/w320/as.png",
    category: "Mehndi",
  },
  {
    id: "6",
    name: "Ahmed",
    country: "Egypt",
    profileIcon: Images.person6,
    flagIcon: "https://flagcdn.com/w320/ad.png",
    category: "Astrologer",
  },
  {
    id: "7",
    name: "Amina",
    country: "Nigeria",
    profileIcon: Images.person7,
    flagIcon: "https://flagcdn.com/w320/ao.png",
    category: "Makeup",
  },
  {
    id: "8",
    name: "Pablo",
    country: "Spain",
    profileIcon: Images.person8,
    flagIcon: "https://flagcdn.com/w320/ai.png",
    category: "Photographer",
  },
  {
    id: "9",
    name: "Li Wei",
    country: "China",
    profileIcon: Images.person9,
    flagIcon: "https://flagcdn.com/w320/aq.png",
    category: "Assistant",
  },
  {
    id: "10",
    name: "Olga",
    country: "Russia",
    profileIcon: Images.person10,
    flagIcon: "https://flagcdn.com/w320/ag.png",
    category: "Mehndi",
  },
  {
    id: "11",
    name: "Hans",
    country: "Germany",
    profileIcon: Images.person11,
    flagIcon: "https://flagcdn.com/w320/ar.png",
    category: "Photographer",
  },
  {
    id: "12",
    name: "Sofia",
    country: "Greece",
    profileIcon: Images.person12,
    flagIcon: "https://flagcdn.com/w320/am.png",
    category: "Makeup",
  },
  {
    id: "13",
    name: "Lucas",
    country: "Brazil",
    profileIcon: Images.person13,
    flagIcon: "https://flagcdn.com/w320/aw.png",
    category: "Astrologer",
  },
  {
    id: "14",
    name: "Anna",
    country: "Sweden",
    profileIcon: Images.person14,
    flagIcon: "https://flagcdn.com/w320/au.png",
    category: "Assistant",
  },
  {
    id: "15",
    name: "Dmitry",
    country: "Ukraine",
    profileIcon: Images.person15,
    flagIcon: "https://flagcdn.com/w320/at.png",
    category: "Mehndi",
  },
  {
    id: "16",
    name: "Nina",
    country: "France",
    profileIcon: Images.person1,
    flagIcon: "https://flagcdn.com/w320/az.png",
    category: "Photographer",
  },
  {
    id: "17",
    name: "Hassan",
    country: "Morocco",
    profileIcon: Images.person3,
    flagIcon: "https://flagcdn.com/w320/bs.png",
    category: "Makeup",
  },
  {
    id: "18",
    name: "Isabella",
    country: "Argentina",
    profileIcon: Images.person8,
    flagIcon: "https://flagcdn.com/w320/bh.png",
    category: "Astrologer",
  },
  {
    id: "19",
    name: "Koji",
    country: "South Korea",
    profileIcon: Images.person5,
    flagIcon: "https://flagcdn.com/w320/bd.png",
    category: "Assistant",
  },
  {
    id: "20",
    name: "Laila",
    country: "Turkey",
    profileIcon: Images.person2,
    flagIcon: "https://flagcdn.com/w320/bb.png",
    category: "Mehndi",
  },
  {
    id: "21",
    name: "Matteo",
    country: "Portugal",
    profileIcon: Images.person7,
    flagIcon: "https://flagcdn.com/w320/by.png",
    category: "Photographer",
  },
  {
    id: "22",
    name: "Fatima",
    country: "Saudi Arabia",
    profileIcon: Images.person11,
    flagIcon: "https://flagcdn.com/w320/be.png",
    category: "Makeup",
  },
  {
    id: "23",
    name: "Mikhail",
    country: "Russia",
    profileIcon: Images.person14,
    flagIcon: "https://flagcdn.com/w320/bz.png",
    category: "Astrologer",
  },
  {
    id: "24",
    name: "Zara",
    country: "Pakistan",
    profileIcon: Images.person4,
    flagIcon: "https://flagcdn.com/w320/bj.png",
    category: "Assistant",
  },
  {
    id: "25",
    name: "Emmanuel",
    country: "Ghana",
    profileIcon: Images.person8,
    flagIcon: "https://flagcdn.com/w320/bt.png",
    category: "Mehndi",
  },
  {
    id: "26",
    name: "Rossie",
    country: "Ghana",
    profileIcon: Images.person8,
    flagIcon: "https://flagcdn.com/w320/bo.png",
    category: "Mehndi",
  },
  {
    id: "27",
    name: "Rebika",
    country: "Ghana",
    profileIcon: Images.person8,
    flagIcon: "https://flagcdn.com/w320/bw.png",
    category: "Mehndi",
  },
  {
    id: "28",
    name: "Lisa",
    country: "Ghana",
    profileIcon: Images.person8,
    flagIcon: "https://flagcdn.com/w320/bv.png",
    category: "Mehndi",
  },
];
